defaults: &defaults
  admin_address: notifier@greenprintmedia.org
  airbrake:
    project_id: 107557
    project_key: 9bb2dea97560fefd2ebfb1d1ca095309
  aws:
    access_key_id: AKIAJRZXYOLH6BJRUFCA
    secret_access_key: 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
  cdn_url: "https://aaa88b80560cd19ec1bb-1e1acd87944e81f870b46ccedb140948.ssl.cf1.rackcdn.com"
<<<<<<< HEAD
  from_address: '"greenprint Learning" <no-reply@greenprintmedia.org>'
  site_url: "https://www.greenprintmedia.org"
=======
  from_address: '"greenprint Learning" <no-reply@greenprintmedia.org>'
  site_url: "https://www.greenprintmedia.org"
>>>>>>> parent of 0bd3464... customize to greenprintmedia
  tweet_streamer: twitter
  twitter:
    consumer_key: nope
    consumer_secret: nope
  gnip:
    username: nope
    password: nope
    client_number: 0
  brand:
<<<<<<< HEAD
    name: greenprint Learning
    domain: greenprintmedia.org
    feedback_address: notifier@greenprintmedia.org
    email_banner: "https://aaa88b80560cd19ec1bb-1e1acd87944e81f870b46ccedb140948.ssl.cf1.rackcdn.com/chrome/owl/mail-header-background.jpg"
    email_logo: "http://learn.greenprint.com/rs/592-NVZ-327/images/VIF-greenprint_02-01.png"
    support_email: "support@greenprintmedia.org"
    twitter: greenprintlrn
    facebook: greenprintlrn
    googleplus: "108098450018287233920"
    internal_emails:
      - twitter@greenprintmedia.org
      - greenprint@greenprint.com
      - newglobalcitizens@greenprintmedia.org
=======
    name: greenprint Learning
    domain: greenprintmedia.org
    feedback_address: notifier@greenprintmedia.org
    email_banner: "https://aaa88b80560cd19ec1bb-1e1acd87944e81f870b46ccedb140948.ssl.cf1.rackcdn.com/chrome/owl/mail-header-background.jpg"
    email_logo: "http://learn.greenprint.com/rs/592-NVZ-327/images/VIF-Participate_02-01.png"
    support_email: "support@greenprintmedia.org"
    twitter: participatelrn
    facebook: participatelrn
    googleplus: "108098450018287233920"
    internal_emails:
      - twitter@greenprintmedia.org
      - participate@greenprint.com
      - newglobalcitizens@greenprintmedia.org
>>>>>>> parent of 0bd3464... customize to greenprintmedia
  swagger: true
  learning_registry: &learning_registry_defaults
    node_url: "https://sandbox.learningregistry.org"
    oauth_consumer_key: admin@greenprintmedia.org
    oauth_consumer_secret: ZL5VwF7BaqSeJljQw+xx4uNerNov3sJf
    oauth_token: node_sign_token
    oauth_token_secret: xdYzoa+iHZVB8NpcyejEA3TTvatVYox8
  joomla: &joomla_defaults
    host: 127.0.0.1
    port: 3306
    username: root
    password: ""
    database: joomla
  mailgun:
    host: "smtp.mailgun.org"
    domain: "mg.greenprintmedia.org"
    port: 25
    user: "notifier@mg.greenprintmedia.org"
    password: "impact-filial-grayling"
  scheduled_messages:
    enabled: false
  measurements: false

development:
  <<: *defaults
  api_url: "http://127.0.0.1:5019/v1"
  secret_key_base: 3fe8057201ce33981d20ddc98ff86114121d58c4c0547cc16cd3fa258433d56cd69966cb6116553676fda5b296e877661b15c8ec1ee70c97940da0b5c297b02b
  segment:
    api_key: bflQvWYHym9lGKzXA7b2pglZunO0KCq6
<<<<<<< HEAD
  from_address: '"greenprint Development" <no-reply@greenprintmedia.org>'
  site_url: "http://local-www.greenprintmedia.org"
  cdn_url: "http://local-www.greenprintmedia.org:5020/dev-assets/cdn"
=======
  from_address: '"greenprint Development" <no-reply@greenprintmedia.org>'
  site_url: "http://local-www.greenprintmedia.org"
  cdn_url: "http://local-www.greenprintmedia.org:5020/dev-assets/cdn"
>>>>>>> parent of 0bd3464... customize to greenprintmedia
  redis:
    namespace: pl
    url: redis://localhost:6379
  pusher:
    app_id: 140007
    key: 510e8e289788e3a7de50
    secret: 6a610a47d916481e5994
  tweet_streamer: twitter
  twitter:
    consumer_key: 3Oqfi0MglDhLOjawFdGInZqlr
    consumer_secret: IGh0w6YTsWxJC72gyr5TmFEZAK1eNSeVnYTRPHV8KRUQtr8ni5
    access_token: 1287343238-rqakMHWNCk8gH2vzPV939UeAgdO2Jje6gz8QOOe
    access_token_secret: 3qnjN9iNBvBk83q0LuX6ghffRlEfbKPhPoALISovQse4H
  gnip:
    username: "admin+gnipapi@greenprintmedia.org"
    password: quid-sneaker-bulldog
    client_number: 1
  measurements: true

test:
  <<: *defaults
  airbrake:
    project_id: 0
    project_key: nope
  cdn_url: "https://cdn.example.com"
  secret_key_base: ecc7a1c9812a28d2dcbc7d8182821a364da195fed962f5f53dd69df9cd41576f00db0b0ef909f2d6499d1df5d7bdf8d8dc5c9efdf77ddccf6f3f6891dea195eb
  segment:
    api_key: nope
  swagger: false
  scheduled_messages:
    enabled: true # Allows enqueue testing, won't send in test

staging:
  <<: *defaults
  api_url: "https://staging-api.greenprintmedia.org/v1"
  redis:
    namespace: pl
    url: redis://localhost:6379
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  segment:
    api_key: 0kU2SUXiDlA4bdWQBO8cJreLLtp0gJI3
<<<<<<< HEAD
  site_url: "https://staging-www.greenprintmedia.org"
  from_address: '"greenprint Learning Staging" <no-reply@greenprintmedia.org>'
=======
  site_url: "https://staging-www.greenprintmedia.org"
  from_address: '"greenprint Learning Staging" <no-reply@greenprintmedia.org>'
>>>>>>> parent of 0bd3464... customize to greenprintmedia
  pusher:
    app_id: 140081
    key: 49225d18402fa4ea522b
    secret: d18ccd85498327f5eb4a
  tweet_streamer: twitter
  twitter:
    consumer_key: tG0Ssv7AzZjGGC2XG8Jh3b3X7
    consumer_secret: LmHH2o58CJftPFkFTQELtplozpWC6bTPx2DqjlwXW0SgMjXPIO
    access_token: 1287343238-llsZa5q1It4roZzUbd2bHOIcJEtAIvieZxmfffS
    access_token_secret: YMgNs2kotoJ1U6gZcrGSXYQC6G3FfPyXpVwCW72GVUBOG
  gnip:
    username: "admin+gnipapi@greenprintmedia.org"
    password: quid-sneaker-bulldog
    client_number: 1
  joomla:
    <<: *joomla_defaults
    port: 3307
    username: <%= ENV["JOOMLA_DB_USERNAME"] %>
    password: <%= ENV["JOOMLA_DB_PASSWORD"] %>
  measurements: true

production:
  <<: *defaults
  api_url: "http://127.0.0.1:8080/v1"
  redis:
    namespace: pl
    url: redis://localhost:6379
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  segment:
    api_key: cUUICQny1hL5EIDFS52Tos5aqE7B4gXp
  pusher:
    app_id: 140082
    key: 78cfc53b2bc07b3a272a
    secret: d3e9c2f109d0beff611f
  swagger: false
  learning_registry:
    <<: *learning_registry_defaults
    node_url: "https://node01.public.learningregistry.net/"
    oauth_consumer_secret: dLcujZFlXC0Ixz+5/TtDNMjbfl30YoGy
    oauth_token_secret: 4OxmYPE0hol8g7fuIpBF+elBgqX+UNQO
  tweet_streamer: gnip
  twitter:
    consumer_key: A4jdkVS00nuM0lZ8uewcu98Us
    consumer_secret: 0ybyFFLfavqeQmo4rMHk6Ar1AoLEm9fUR0zsxj0WEli5UvgcM7
    access_token: 1287343238-4UQLc0h4YXpim6ZhemhsAE9Oo6Hru4cSkv1HFxn
    access_token_secret: 0b8tFLZk98RHSW47QfCWXYWJMTWq2YBWQKcKUx2DbQiDO
  gnip:
    username: "admin+gnipapi@greenprintmedia.org"
    password: quid-sneaker-bulldog
    client_number: 2
  joomla:
    <<: *joomla_defaults
    port: 3307
    username: <%= ENV["JOOMLA_DB_USERNAME"] %>
    password: <%= ENV["JOOMLA_DB_PASSWORD"] %>
  scheduled_messages:
    enabled: true
